name: Check docs and README.md

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: --deny warnings

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}
          gc-max-store-size-linux: 8G
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            xtask/target
          key: cargo-${{ runner.os }}

      - name: Check README.md
        run: |
          cargo xtask readme
          git diff --exit-code README.md
        shell: &shell "nix develop --impure -c bash -e {0}"
      - name: Check cargo doc
        run: |
          cargo doc --features ngx/vendored --workspace
        shell: *shell
