name: Check docs and README.md

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo xtask readme && git diff --exit-code README.md
      - run: cargo doc --features ngx/vendored
